baseURL = 'http://christisking.github.io/'
languageCode = 'en-us'
title = 'Christ Is King'
theme = 'hugo-book'

[params]

# Light or Dark
BookTheme = 'auto'
BookMenuBundle = '/menu'
BookToC = true
BookLogo = 'single_cross.png'

[markup.goldmark.renderer]
unsafe = false